# pyproject.toml
[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bentomail"
version = "1.0.0"
authors = [
    { name="Jason Marencic" }
]
description = "An elegant, decoupled HTML email dashboard layout engine using dataclasses and Jinja2."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Communications :: Email"
]
# Core dependencies only
dependencies = [
    "Jinja2>=3.1.6",
    "python-dotenv>=1.2.2"
]

# Optional dependencies for users who want chart rendering
[project.optional-dependencies]
charts = ["matplotlib>=3.11.0"]

[project.urls]
"Homepage" = "<gitlab or github url>" 

[tool.setuptools.packages.find]
where = ["."]
include = ["bentomail*"]  # Note: If you rename your source folder from 'emailer' to 'bentomail', update this!

[tool.setuptools.package-data]
"bentoemail" = ["templates/*.jinja"] 
